### ISSUE TITLE
Feature request: dragon riding default music outside of races

### ISSUE THREAD

**Issue by Greybaine** [Shushuda/DragonSpeedway#2]
Hey there! Thank you for building this addon! 

I was wondering, would it be possible to play music when mounting the dragon outside of races? I love the default dragon riding music and would love to hear it when ever I am flying haha

**Comment by Shushuda** [comment]
Hello! Glad you enjoy it!

I'm actually working on this exact feature! Well, was working on it, but I've recently got a neck injury and I had to postpone any code writing for a bit. But it's in the works!

I've planned to have a few options to play music outside of races, depending on what triggers the music. One of these options was supposed to work like FF14's mount music - plays as soon as you mount up and stops on dismount. Another option would start the music only on clicking dragonriding skills etc.

I'm also trying to rewrite the code to be much easier to add new music. Mostly move the external "write this line of code for each music file" inside the game, a bit like WeakAuras is doing it. The backend is the same, it's just removing the need to write anything inside addon files - you'd do it inside the game now and you'd provide the file and song names only, the addon would generate the rest of the code for you in the background. Should be much more user friendly.

But it's a bigger rewrite that now has to wait because my neck is killing me, lol.

I did add camera work some time ago (camera zoom changes on mount up / dismount), but didn't upload it inside any release yet. So the majority of the code for your feature is already there. I could add some simple "play music on mount up FF14-style" to it and upload it as a beta release, so you can at least have this feature working already. I need to fix my neck first, though.

**Comment by Greybaine** [comment]
Hey there! Thank you for following up :) 

I am sorry to hear about your neck. :( I hope you have a speedy recovery!

I am excited to hear that this feature is already in the works as it was one the first things that I wanted when I heard the dragon riding racing music haha. But, yes please take care of your self as health is far more important. 

I will subscribe to updates to keep up with the project :) 

Thank you for your work into this!

**Comment by Shushuda** [comment]
Hey, I've had a moment of not-so-crippling-pain today morning and added the option. It will play default dragonriding music on mount up, outside of races. It won't play any custom music outside of races though, that will require a bit more work. But at least now you can play that default song when riding around. :D
Let me know if there are any bugs!

I will upload it today as a beta release, here and on CurseForge.

The cut-off on dismount is sometimes a bit sudden, with no nice fade out, but tbf I have no idea how to fix that or if that's even possible to fix, lol. That's just how Blizzard's StopMusic() funtion is working, I guess. It's not as jarring when finishing a race, but kinda jarring on dismount. Can't do anything about it though.

**Comment by Greybaine** [comment]
ah! Amazing! Thank you so much :D 

I am psyched to start hearing that dragon racing music more often haha. Thank you again and I appreciate the work you put into this. I see there are some discussions on reddit about the same feature so I am sure players will be pumped about this :D 

I hope all is well!
